version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
    - dependencies
    ignore:
    - dependency-name: "*"
      versions: ["*ea*"]
  - package-ecosystem: maven
    directory: "/demo"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
    ignore:
    - dependency-name: "*"
      versions: ["*ea*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
